#!/usr/bin/env sh

USERID=$(id -u)
GROUPID=$(id -g)

echo "------ DOCKER HUB BUILD HOOK - START -------"

docker build --build-arg userid=$USERID --build-arg groupid=$GROUPID -t $IMAGE_NAME .

echo "------ DOCKER HUB BUILD HOOK - END -------"
