#!/usr/bin/env sh

USERID=1003
GROUPID=1003

echo "------ DOCKER HUB BUILD HOOK - START -------"

docker build --build-arg userid=$USERID --build-arg groupid=$GROUPID -t $IMAGE_NAME .

echo "------ DOCKER HUB BUILD HOOK - END -------"
