#!/bin/bash
# Copyright (C) 2018 Luxoft
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR
# BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES
# OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.
#
# For further information see LICENSE
#

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <install_dir> <sdk_dir>"
    exit 1
fi

# Store parameters
INSTALL_DIR="$1"
SDK_DIR="$2"

# Remove the -dev version
SCRIPT="$(ls ${SDK_DIR}/pelux-*toolchain*.sh)"

if [ ! -f "${SCRIPT}" ]; then
    echo "Cannot find SDK installation script ${SCRIPT}"
    exit -1
fi

echo "Running installation script: $SCRIPT"

chmod a+x "${SCRIPT}"
"${SCRIPT}" -d "${INSTALL_DIR}" -y
