#!/bin/bash
#
# Copyright (C) 2018 Luxoft
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR
# BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES
# OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.
#
# For further information see LICENSE
#

SDKDIR=$1
PROJECT=$2

if [ "${SDKDIR}" = "" ]; then
    echo "Missing argument 1: SDK destination directory"
    exit -1
fi

echo "Checking out example $PROJECT"
git clone "https://github.com/Pelagicore/$PROJECT.git"

# The shell script we are about to source defines some aliases. In order for
# these to work, we need to set the expand_aliases bash option:

shopt -s expand_aliases

ENV_SCRIPT="$(echo ${SDKDIR}/environment-setup-*)"
source "${ENV_SCRIPT}"

echo "Building $PROJECT"

cd "$PROJECT"
mkdir build
cd build
cmake ..
make
make install
