#!/bin/bash
#
# Copyright (C) 2019 Luxoft Sweden AB
#


if [ $# -ne 2 ]; then
    echo "Usage: $0 <build_dir> <archive_dir>"
    exit 1
fi

BUILD_DIR="$1"
ARCHIVE_DIR="$2"

IMAGE_DIR="${BUILD_DIR}/tmp/deploy/images"
SDK_DIR="${BUILD_DIR}/tmp/deploy/sdk"
LOG_DIR="${BUILD_DIR}/tmp/log"

INTEL_ARCH="intel-corei7-64"
ARP_ARCH="arp"
RPI_ARCH="raspberrypi3"
QEMU_ARCH="qemux86-64"
JETSON_ARCH="jetson-tx2"

IMAGE_BASENAME="core-image-pelux"
SDK_BASENAME="pelux-glibc"

# If there is an QEMU directory
if [ -d ${IMAGE_DIR}/${QEMU_ARCH} ]; then
    echo "Archiving QEMU image to $ARCHIVE_DIR"
    mv ${IMAGE_DIR}/${QEMU_ARCH}/${IMAGE_BASENAME}-*.rootfs.ext4 $ARCHIVE_DIR
fi

# Copy the logs
if [ -d ${LOG_DIR}/isafw-logs ]; then
	echo "Archiving logs to $ARCHIVE_DIR"
	mv ${LOG_DIR}/isafw-report_*/* $ARCHIVE_DIR
fi

# If there is an Intel directory
if [ -d ${IMAGE_DIR}/${INTEL_ARCH} ]; then
    echo "Archiving Intel image to $ARCHIVE_DIR"
    mv ${IMAGE_DIR}/${INTEL_ARCH}/${IMAGE_BASENAME}-*rootfs.wic $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${INTEL_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bmap $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${INTEL_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bz2 $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${INTEL_ARCH}/${IMAGE_BASENAME}-*20*.swu $ARCHIVE_DIR
fi

# If there is an ARP directory

if [ -d ${IMAGE_DIR}/${ARP_ARCH} ]; then
    echo "Archiving ARP image to $ARCHIVE_DIR"
    mv ${IMAGE_DIR}/${ARP_ARCH}/${IMAGE_BASENAME}-*rootfs.wic $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${ARP_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bmap $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${ARP_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bz2 $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${ARP_ARCH}/${IMAGE_BASENAME}-*20*.swu $ARCHIVE_DIR
fi

# If there is an RPI directory
if [ -d ${IMAGE_DIR}/${RPI_ARCH} ]; then
    echo "Archiving RPI image to $ARCHIVE_DIR"
    mv ${IMAGE_DIR}/${RPI_ARCH}/${IMAGE_BASENAME}-*rootfs.wic $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${RPI_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bmap $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${RPI_ARCH}/${IMAGE_BASENAME}-*rootfs.wic.bz2 $ARCHIVE_DIR
    mv ${IMAGE_DIR}/${RPI_ARCH}/${IMAGE_BASENAME}-*20*.swu $ARCHIVE_DIR
fi

# If there is a Jetson TX2 directory
if [ -d ${IMAGE_DIR}/${JETSON_ARCH} ]; then
    echo "Archiving Jetson TX2 image to $ARCHIVE_DIR"
    mv ${IMAGE_DIR}/${JETSON_ARCH}/${IMAGE_BASENAME}-*.tegraflash.zip $ARCHIVE_DIR
fi

# Copy the SDK
if [ -d ${SDK_DIR} ]; then
    echo "Archiving SDK to $ARCHIVE_DIR"
    mv ${SDK_DIR}/${SDK_BASENAME}-*.sh $ARCHIVE_DIR
fi


