#!/bin/bash
# Copyright (C) 2018 Luxoft
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR
# BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES
# OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.
#
# For further information see LICENSE
#

if [ $# -ne 2 ]; then
    echo "Usage: $0 <build_dir> <archive_dir>"
    exit 1
fi

BUILD_DIR="$1"
ARCHIVE_DIR="$2"

IMAGE_DIR="${BUILD_DIR}/tmp/deploy/images"
SDK_DIR="${BUILD_DIR}/tmp/deploy/sdk"

RPI_ARCH="raspberrypi3"
INTEL_ARCH="intel-corei7-64"

IMAGE_BASENAME="core-image-pelux"
SDK_BASENAME="pelux-glibc"

# If there is a rpi directory available
if [ -d ${IMAGE_DIR}/${RPI_ARCH} ]; then
    echo "Archiving rPi image to $ARCHIVE_DIR"
    cp ${IMAGE_DIR}/${RPI_ARCH}/${IMAGE_BASENAME}-*.rpi-sdimg $ARCHIVE_DIR
fi

# If there is an intel directory
if [ -d ${IMAGE_DIR}/${INTEL_ARCH} ]; then
    echo "Archiving Intel image to $ARCHIVE_DIR"
    cp ${IMAGE_DIR}/${INTEL_ARCH}/${IMAGE_BASENAME}-*.wic $ARCHIVE_DIR
fi

# Copy the SDK
if [ -d ${SDK_DIR} ]; then
    echo "Archiving SDK to $ARCHIVE_DIR"
    cp ${SDK_DIR}/${SDK_BASENAME}-*.sh $ARCHIVE_DIR
fi

# Copy the downloads directory
if [ -d ${BUILD_DIR}/downloads ]; then
    echo "Archiving downloads to $ARCHIVE_DIR"
    cp -r ${BUILD_DIR}/downloads $ARCHIVE_DIR
fi
