#!/bin/bash
#
# Copyright (C) 2017 Luxoft
#

MANIFEST="$1"

if [ "${MANIFEST}" = "" ]; then
    echo "Missing argument 1: manifest"
    exit -1
fi

# Parameter expansion with default values
SYNC_DIR="${2:-/vagrant}"
YOCTO_DIR="${3:-pelux_yocto}"

echo "Running repo init with the following settings:"
echo "manifest=${MANIFEST}"
echo "sync dir=${SYNC_DIR}"
echo "yocto dir=${YOCTO_DIR}"

# In order to get repo tool to be able to init from pull-requests, there
# has to be a branch available in /refs/heads. This is facilitated by
# syncing the git repositroy on the host (in which this file is located) into
# the vagrant machine. The git repository is fetched from the host since the
# host already fetched the correct refs via the Jenkinsfile.

# Copy the host repo to ensure that no later git commands destroy anything.
COPY_DIR="/tmp/git_repo"
cp -r ${SYNC_DIR} ${COPY_DIR}

# After making a copy of the synced git directory it is made sure that there is
# a branch, in this case called master, in /refs/heads containing the latest commits
# which we can point to using repo init.

# Make sure there is a master branch and that it is pointing to the latest commit.
cd ${COPY_DIR}

# Check if master branch exists
git rev-parse --verify master
if [ $? == 0 ]; then
    git branch -D master
fi

git checkout -b master
cd -

# Now everything is set to be able to do repo init from the copied git repository.
# Manifest is provided via environment variables set at running vagrant up.

# Clone recipes
mkdir "$YOCTO_DIR"
cd "$YOCTO_DIR"
time repo init -u ${COPY_DIR} -m ${MANIFEST} -b master
time repo sync
